version: "2"
services:
  metabase:
    image: metabase/metabase:v0.42.3
    env_file: ./env
    volumes:
      - ./data/metabase-data:/metabase-data
    ports:
      - 3000:3000
    depends_on:
      - postgres-mb

  postgres-mb:
    build:
      context: ps_build
      dockerfile: Dockerfile
    env_file: ./env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./posgreinit:/docker-entrypoint-initdb.d
    ports:
      - 5434:5434
    command: -p 5434
    container_name: "db"