version: "2"
services:
  metabase:
    image: metabase/metabase:v0.42.3
    env_file: ./env
    volumes:
      - ./data/metabase-data:/metabase-data
    ports:
      - 3000:3000
    depends_on:
      - postgres-mb

  postgres-mb:
    image: postgres:alpine3.16
    env_file: ./env
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
      - ./posgreinit:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    container_name: "db"